build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  LongMethod:
    active: true
    threshold: 80
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    active: true
    threshold: 20

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    active: true

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  ReturnCount:
    active: true
    max: 4
  WildcardImport:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: true
